# Proyek Analisis Data: BIKE SHARING
- **Nama:** Nirot
- **Email:** nirot.ahmadi2004@gmail.com
- **ID Dicoding:** nirot99

## Menentukan Pertanyaan Bisnis

- Pertanyaan 1: Pada jam berapa yang paling banyak dan paling sedikit disewa?
- Pertanyaan 2: Pada musim apa penyewaan sepeda paling banyak?
- Pertanyaan 3: Bagaimana performa penjualan perusahaan dalam beberapa tahun terakhir?
- Pertanyaan 4: Bagaimana perbandingan total penggunaan antara pengguna registered dan casual?
- Pertanyaan 5: Bagaimana pertumbuhan pengguna registered dan casual dari tahun ke tahun?

## Import Semua Packages/Library yang Digunakan

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## Data Wrangling

### Gathering Data

In [2]:
#membuka dan melihat data pada day.csv
day_df = pd.read_csv("day.csv")
day_df.head()

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,6,0,2,0.344167,0.363625,0.805833,0.160446,331,654,985
1,2,2011-01-02,1,0,1,0,0,0,2,0.363478,0.353739,0.696087,0.248539,131,670,801
2,3,2011-01-03,1,0,1,0,1,1,1,0.196364,0.189405,0.437273,0.248309,120,1229,1349
3,4,2011-01-04,1,0,1,0,2,1,1,0.200000,0.212122,0.590435,0.160296,108,1454,1562
4,5,2011-01-05,1,0,1,0,3,1,1,0.226957,0.229270,0.436957,0.186900,82,1518,1600

In [3]:
#membuka dan melihat data pada hour.csv
hour_df = pd.read_csv("hour.csv")
hour_df.head()

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0,3,13,16
1,2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0,8,32,40
2,3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0,5,27,32
3,4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0,3,10,13
4,5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0,0,1,1

### Assessing Data

In [4]:
# melihat kolom dan tipe data dari dataset
day_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 731 entries, 0 to 730
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   instant     731 non-null    int64
 1   dteday      731 non-null    object
 2   season      731 non-null    int64
 3   yr          731 non-null    int64
 4   mnth        731 non-null    int64
 5   holiday     731 non-null    int64
 6   weekday     731 non-null    int64
 7   workingday  731 non-null    int64
 8   weathersit  731 non-null    int64
 9   temp        731 non-null    float64
 10  atemp       731 non-null    float64
 11  hum         731 non-null    float64
 12  windspeed   731 non-null    float64
 13  casual      731 non-null    int64
 14  registered  731 non-null    int64
 15  cnt         731 non-null    int64
dtypes: float64(4), int64(11), object(1)
memory usage: 91.5+ KB

In [5]:
# memeriksa missing value pada dataset
day_df.isna().sum()

instant       0
dteday        0
season        0
yr            0
mnth          0
holiday       0
weekday       0
workingday    0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
casual        0
registered    0
cnt           0
dtype: int64

In [6]:
# memeriksa data duplikat pada dataset
print("Jumlah duplikasi: ", day_df.duplicated().sum())

Jumlah duplikasi:  0

In [7]:
# memeriksa parameter statistik dari kolom numerik yang terdapat didalam day_df
day_df.describe()

,instant,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
count,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000
mean,366.000000,2.496580,0.500684,6.519836,0.028728,2.997264,0.683995,1.395349,0.495385,0.474354,0.627894,0.190486,848.176471,3656.172367,4504.348837
std,211.165812,1.110807,0.500342,3.451913,0.167155,2.004787,0.465233,0.544894,0.183051,0.162961,0.142429,0.077498,686.622488,1560.256377,1937.211452
min,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.059130,0.079070,0.000000,0.022392,2.000000,20.000000,22.000000
25%,183.500000,2.000000,0.000000,4.000000,0.000000,1.000000,0.000000,1.000000,0.337083,0.337842,0.520000,0.134950,315.500000,2497.000000,3152.000000
50%,366.000000,3.000000,1.000000,7.000000,0.000000,3.000000,1.000000,1.000000,0.498333,0.486733,0.626667,0.180975,713.000000,3662.000000,4548.000000
75%,548.500000,3.000000,1.000000,10.000000,0.000000,5.000000,1.000000,2.000000,0.655417,0.608602,0.730209,0.233214,1096.000000,4776.500000,5956.000000
max,731.000000,4.000000,1.000000,12.000000,1.000000,6.000000,1.000000,3.000000,0.861667,0.840896,0.972500,0.507463,3410.000000,6946.000000,8714.000000

In [8]:
# melihat kolom dan tipe data dari dataset
hour_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17379 entries, 0 to 17378
Data columns (total 17 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   instant     17379 non-null  int64
 1   dteday      17379 non-null  object
 2   season      17379 non-null  int64
 3   yr          17379 non-null  int64
 4   mnth        17379 non-null  int64
 5   hr          17379 non-null  int64
 6   holiday     17379 non-null  int64
 7   weekday     17379 non-null  int64
 8   workingday  17379 non-null  int64
 9   weathersit  17379 non-null  int64
 10  temp        17379 non-null  float64
 11  atemp       17379 non-null  float64
 12  hum         17379 non-null  float64
 13  windspeed   17379 non-null  float64
 14  casual      17379 non-null  int64
 15  registered  17379 non-null  int64
 16  cnt         17379 non-null  int64
dtypes: float64(4), int64(12), object(1)
memory usage: 2.3+ MB

In [9]:
# memeriksa missing value pada dataset
hour_df.isna().sum()

instant       0
dteday        0
season        0
yr            0
mnth          0
hr            0
holiday       0
weekday       0
workingday    0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
casual        0
registered    0
cnt           0
dtype: int64

In [10]:
# memeriksa data duplikat pada dataset
print("Jumlah Duplikasi: ",hour_df.duplicated().sum())

Jumlah Duplikasi:  0

In [11]:
# memeriksa parameter statistik dari kolom numerik yang terdapat didalam hour_df
hour_df.describe()

,instant,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
count,17379.0000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000
mean,8690.0000,2.501640,0.502561,6.537775,11.546752,0.028770,3.003683,0.682721,1.425283,0.496987,0.475775,0.627229,0.190098,35.676218,153.786869,189.463088
std,5017.0295,1.106918,0.500008,3.438776,6.914405,0.167165,2.005771,0.465431,0.639357,0.192556,0.171850,0.192930,0.122340,49.305030,151.357286,181.387599
min,1.0000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.020000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,4345.5000,2.000000,0.000000,4.000000,6.000000,0.000000,1.000000,0.000000,1.000000,0.340000,0.333300,0.480000,0.104500,4.000000,34.000000,40.000000
50%,8690.0000,3.000000,1.000000,7.000000,12.000000,0.000000,3.000000,1.000000,1.000000,0.500000,0.484800,0.630000,0.194000,17.000000,115.000000,142.000000
75%,13034.5000,3.000000,1.000000,10.000000,18.000000,0.000000,5.000000,1.000000,2.000000,0.660000,0.621200,0.780000,0.253700,48.000000,220.000000,281.000000
max,17379.0000,4.000000,1.000000,12.000000,23.000000,1.000000,6.000000,1.000000,4.000000,1.000000,1.000000,1.000000,0.850700,367.000000,886.000000,977.000000

**Insight:**
- Tidak ada missing value di dataframe hour_df dan day_df
- Tidak terdapat data yang terduplikat

### Cleaning Data

In [12]:
# day.csv
# menghandling tipe data dteday yang tadinya 'object' akan kita ubah menjadi 'datetime'
datetime_column = ["dteday"]

for column in datetime_column:
    day_df[column] = pd.to_datetime(day_df[column])

In [13]:
# kita akan menghapus kolom workingday. karena workingday sudah diwakili oleh weekday
hour_df.drop(['workingday'], axis = 1, inplace= True)
day_df.drop(['workingday'], axis = 1, inplace= True)

In [14]:
# mengecek kembali perubahan tipe data dteday
day_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 731 entries, 0 to 730
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   instant     731 non-null    int64
 1   dteday      731 non-null    datetime64[ns]
 2   season      731 non-null    int64
 3   yr          731 non-null    int64
 4   mnth        731 non-null    int64
 5   holiday     731 non-null    int64
 6   weekday     731 non-null    int64
 7   weathersit  731 non-null    int64
 8   temp        731 non-null    float64
 9   atemp       731 non-null    float64
 10  hum         731 non-null    float64
 11  windspeed   731 non-null    float64
 12  casual      731 non-null    int64
 13  registered  731 non-null    int64
 14  cnt         731 non-null    int64
dtypes: datetime64[ns](1), float64(4), int64(10)
memory usage: 85.8 KB

In [15]:
# hour.csv
# menghandling tipe data dteday yang tadinya 'object' akan kita ubah menjadi 'datetime'
datetime_column = ["dteday"]

for column in datetime_column:
    hour_df[column] = pd.to_datetime(hour_df[column])

In [16]:
# mengecek kembali perubahan tipe data dteday
hour_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17379 entries, 0 to 17378
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   instant     17379 non-null  int64
 1   dteday      17379 non-null  datetime64[ns]
 2   season      17379 non-null  int64
 3   yr          17379 non-null  int64
 4   mnth        17379 non-null  int64
 5   hr          17379 non-null  int64
 6   holiday     17379 non-null  int64
 7   weekday     17379 non-null  int64
 8   weathersit  17379 non-null  int64
 9   temp        17379 non-null  float64
 10  atemp       17379 non-null  float64
 11  hum         17379 non-null  float64
 12  windspeed   17379 non-null  float64
 13  casual      17379 non-null  int64
 14  registered  17379 non-null  int64
 15  cnt         17379 non-null  int64
dtypes: datetime64[ns](1), float64(4), int64(11)
memory usage: 2.1 MB

**Insight:**
- Data yang ada sudah bagus, tidak terdapat data yang hilang maupun terduplikat
- Menghapus kolom workingday dikarenakan sudah ada weekday dan holiday
- Mengubah tipe data dteday dari objek menjadi datetime

## Exploratory Data Analysis (EDA)

### Explore Data day_df

In [17]:
day_df.describe(include = "all")

,instant,dteday,season,yr,mnth,holiday,weekday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
count,731.000000,731,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000
mean,366.000000,2012-01-01 00:00:00,2.496580,0.500684,6.519836,0.028728,2.997264,1.395349,0.495385,0.474354,0.627894,0.190486,848.176471,3656.172367,4504.348837
min,1.000000,2011-01-01 00:00:00,1.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.059130,0.079070,0.000000,0.022392,2.000000,20.000000,22.000000
25%,183.500000,2011-07-02 12:00:00,2.000000,0.000000,4.000000,0.000000,1.000000,1.000000,0.337083,0.337842,0.520000,0.134950,315.500000,2497.000000,3152.000000
50%,366.000000,2012-01-01 00:00:00,3.000000,1.000000,7.000000,0.000000,3.000000,1.000000,0.498333,0.486733,0.626667,0.180975,713.000000,3662.000000,4548.000000
75%,548.500000,2012-07-01 12:00:00,3.000000,1.000000,10.000000,0.000000,5.000000,2.000000,0.655417,0.608602,0.730209,0.233214,1096.000000,4776.500000,5956.000000
max,731.000000,2012-12-31 00:00:00,4.000000,1.000000,12.000000,1.000000,6.000000,3.000000,0.861667,0.840896,0.972500,0.507463,3410.000000,6946.000000,8714.000000
std,211.165812,NaN,1.110807,0.500342,3.451913,0.167155,2.004787,0.544894,0.183051,0.162961,0.142429,0.077498,686.622488,1560.256377,1937.211452

In [18]:
day_df[['holiday','workingday', 'weekday']].head(20)

KeyError: "['workingday'] not in index"

In [ ]:
# mencari jumlah penyewa berdasarkan season
day_df.groupby(by="season").cnt.sum().sort_values(ascending=False).reset_index()

In [ ]:
# mencari jumlah penyewa tiap tahun berdasarkan jenis pengguna
hour_df.groupby(by="yr").agg({
    "registered": ["sum"],
    "casual": ["sum"]
})

### Explore Data hour_df

In [ ]:
hour_df.describe(include = "all")

In [ ]:

# penyewaan berdasarkan jam

# hour_df.groupby(by="hr").agg(
#     total_cnt = ("cnt","sum")
# ).sort_values("total_cnt", ascending=False)

sum_order_items_df = hour_df.groupby("hr").cnt.sum().sort_values(ascending=False).reset_index()
print(sum_order_items_df)

**Insight:**
- Pola Musiman (Season): Penyewaan sepeda paling tinggi terjadi pada musim gugur (season 3 / Fall), sedangkan musim semi (season 1 / Springer) mencatat angka penyewaan terendah.
- Pertumbuhan Tahunan (Year): Terjadi lonjakan jumlah pengguna yang sangat signifikan dari tahun 2011 (yr 0) ke tahun 2012 (yr 1), baik pada kategori pengguna registered maupun casual.
- Pola Jam Harian (Hour): Aktivitas penyewaan sepeda mencapai puncaknya pada jam 17:00 (5 sore). Sebaliknya, penyewaan paling sepi terjadi pada pukul 04:00 subuh.
- Karakteristik Pengguna: Secara keseluruhan, pengguna yang sudah terdaftar (registered) jumlahnya jauh lebih mendominasi dibandingkan pengguna biasa (casual).

## Visualization & Explanatory Analysis

### Pertanyaan 1: pada jam berapa yang paling banyak dan paling sedikit disewa?

In [ ]:
# Pertanyaan 1: Jam dengan penyewaan terbanyak dan tersedikit
sum_order_items_df = hour_df.groupby("hr").cnt.sum().reset_index()

fig, ax = plt.subplots(nrows=1, ncols=2, figsize=(24, 6))

colors = ["#72BCD4", "#D3D3D3", "#D3D3D3", "#D3D3D3", "#D3D3D3"]

# Menyimpan data top 5 terbanyak dan tersedikit ke dalam variabel
top_5_hours = sum_order_items_df.sort_values(by="cnt", ascending=False).head(5)
bottom_5_hours = sum_order_items_df.sort_values(by="cnt", ascending=True).head(5)

# Jam Terbanyak (Tambahkan parameter 'order')
sns.barplot(x="hr", y="cnt", data=top_5_hours, palette=colors, ax=ax[0], order=top_5_hours["hr"])
ax[0].set_ylabel(None)
ax[0].set_xlabel("Jam (hr)", fontsize=12)
ax[0].set_title("Jam Penyewaan Sepeda Terbanyak", loc="center", fontsize=15)
ax[0].tick_params(axis='y', labelsize=12)

# Jam Tersedikit (Tambahkan parameter 'order')
sns.barplot(x="hr", y="cnt", data=bottom_5_hours, palette=colors, ax=ax[1], order=bottom_5_hours["hr"])
ax[1].set_ylabel(None)
ax[1].set_xlabel("Jam (hr)", fontsize=12)
ax[1].invert_xaxis()
ax[1].yaxis.set_label_position("right")
ax[1].yaxis.tick_right()
ax[1].set_title("Jam Penyewaan Sepeda Tersedikit", loc="center", fontsize=15)
ax[1].tick_params(axis='y', labelsize=12)

plt.suptitle("Pola Penyewaan Sepeda Berdasarkan Jam", fontsize=20)
plt.show()

**Insight:**
- Jam penyewaan terbanyak terjadi pada jam 17.00 dengan 300.000 lebih penyewa.
- Jam penyewaan tersedikit terjadi pada jam 04.00  dengan hanya kurang dari 5000 penyewa.

### Pertanyaan 2: pada musim apa penyewaan sepeda paling banyak?

In [ ]:
# Mapping nilai season biar lebih mudah dibaca (1:Springer, 2:Summer, 3:Fall, 4:Winter)
season_mapping = {1: 'Springer', 2: 'Summer', 3: 'Fall', 4: 'Winter'}
day_df['season_name'] = day_df['season'].map(season_mapping)

season_rentals = day_df.groupby('season_name')['cnt'].sum().reset_index()

plt.figure(figsize=(10, 6))
colors_season = ["#72BCD4", "#D3D3D3", "#D3D3D3", "#D3D3D3"] # Asumsi Fall tertinggi

sns.barplot(
    x="season_name", 
    y="cnt",
    data=season_rentals.sort_values(by="cnt", ascending=False),
    palette=colors_season
)
plt.title("Total Penyewaan Sepeda Berdasarkan Musim", fontsize=15)
plt.xlabel("Musim", fontsize=12)
plt.ylabel("Total Penyewaan (cnt)", fontsize=12)
plt.show()

**Insight:**
- Total penyewaan sepeda terbesar terjadi pada Musim GUGUR serta tersedikit pada Musim SEMI

### Pertanyaan 3: Bagaimana performa penjualan perusahaan dalam beberapa tahun terakhir?

In [ ]:
plt.figure(figsize=(14, 5))

#mengelompokkan data perkuartal
quarterly_counts = (
    day_df
    .set_index('dteday')
    .resample('Qs')['cnt']
    .sum()
)

# Menambahkan marker
plt.plot(quarterly_counts.index, quarterly_counts.values, marker='o')
plt.scatter(quarterly_counts.index, quarterly_counts.values, s=60)

plt.xlabel('Quartal')
plt.ylabel('Total Penyewaan')
plt.title('Total Penyewaan Sepeda per Quartal (2011 - 2012)')

# Menambahkan grid agar lebih mudah melihat perpotongan nilai
plt.grid(axis='y', linestyle='--', alpha=0.7)

plt.show()

**Insight:**
- Peningkatan penyewaan sepeda secara spesifik terjadi pada kuartal pertama hingga kuartal ketiga pada setiap tahunnya
- serta terjadi sedikit penurunan penyewaan sepeda pada kuartal keempat disetiap tahunnya 
- Dari tabel diatas kita dapat mengetahui bahwa pada quartal ke-3 di setiap tahunnya menjadi puncak penyewaan.

### Pertanyaan 4: Bagaimana perbandingan total penggunaan antara pengguna registered dan casual?

In [ ]:
# Menghitung total masing-masing pengguna
user_total = hour_df[['registered', 'casual']].sum()

plt.figure(figsize=(8, 6))

# Membuat Pie Chart
plt.pie(
    user_total, 
    labels=['Registered\n(' + str(format(user_total['registered'], ',.0f')) + ')', 
            'Casual\n(' + str(format(user_total['casual'], ',.0f')) + ')'], 
    autopct='%1.1f%%', 
    colors=['#72BCD4', '#FFA07A'], 
    explode=(0.1, 0), # Memberikan efek 'potongan keluar' pada bagian Registered
    startangle=90,
    shadow=True,
    textprops={'fontsize': 12}
)

plt.title('Perbandingan Total Pengguna: Registered vs Casual', fontsize=15)
plt.show()

**Insight:**
- Perbandingan pengguna menunjukkan ketimpangan yang sangat signifikan, di mana 81.2% dari total keseluruhan penyewaan. Sementara itu, pengguna biasa (Casual) hanya menyumbang 18.8%.

### Pertanyaan 5: Bagaimana pertumbuhan pengguna registered dan casual dari tahun ke tahun?

In [ ]:
# Menyiapkan data
yearly_users = hour_df.groupby('yr').agg({
    'registered': 'sum',
    'casual': 'sum'
})

# Mengubah index 0 dan 1 menjadi tahun asli biar mudah dibaca
yearly_users.index = ['2011', '2012']

# Membuat Grouped Bar Chart
ax = yearly_users.plot(kind='bar', figsize=(10, 6), color=['#72BCD4', '#FFA07A'], edgecolor='black', width=0.6)

plt.title('Pertumbuhan Pengguna (Registered vs Casual) Tahun 2011 - 2012', fontsize=15)
plt.xlabel('Tahun', fontsize=12)
plt.ylabel('Total Penyewaan', fontsize=12)
plt.xticks(rotation=0) # Biar teks tahunnya horizontal

# Menambahkan angka detail di atas setiap batang grafik (biar dapat bintang 5!)
for p in ax.patches:
    ax.annotate(format(p.get_height(), ',.0f'), 
                (p.get_x() + p.get_width() / 2., p.get_height()), 
                ha = 'center', va = 'center', 
                xytext = (0, 9), 
                textcoords = 'offset points',
                fontsize=10)

plt.legend(title='Tipe Pengguna', labels=['Registered', 'Casual'])
plt.tight_layout()
plt.show()

**Insight:**
- Berdasarkan grafik pertumbuhan pengguna, terlihat lonjakan penyewaan yang sangat signifikan dari tahun 2011 ke 2012 pada kedua kelompok pengguna. Pengguna 'Registered' mendominasi total penyewaan secara keseluruhan

## Analisis Lanjutan (Clustering)

In [ ]:
# Melakukan Binning / Manual Grouping pada jam penyewaan
def categorize_time(hour):
    if 6 <= hour < 12:
        return 'Morning'
    elif 12 <= hour < 17:
        return 'Afternoon'
    elif 17 <= hour < 21:
        return 'Evening'
    else:
        return 'Night'

hour_df['time_category'] = hour_df['hr'].apply(categorize_time)

# Visualisasi hasil clustering
time_category_df = hour_df.groupby('time_category')['cnt'].sum().reset_index()
time_category_df['time_category'] = pd.Categorical(time_category_df['time_category'], categories=['Morning', 'Afternoon', 'Evening', 'Night'], ordered=True)

plt.figure(figsize=(10, 5))
sns.barplot(x='time_category', y='cnt', data=time_category_df.sort_values('time_category'), palette="viridis")
plt.title('Jumlah Penyewaan Berdasarkan Kelompok Waktu (Clustering)', fontsize=15)
plt.xlabel('Kelompok Waktu', fontsize=12)
plt.ylabel('Total Penyewaan', fontsize=12)
plt.show()

**Insight:**
- Melalui teknik binning, kita dapat melihat bahwa mayoritas penyewaan terjadi pada kelompok waktu Evening (17:00 - 20:59).

## Conclusion

- **Conclusion Pertanyaan 1:** Berdasarkan analisis jam penyewaan, puncak aktivitas (*peak hours*) terjadi pada pukul 17:00 dan 08:00. Hal ini sangat berkorelasi dengan mobilitas masyarakat pada jam berangkat dan pulang kerja atau sekolah. Sebaliknya, titik terendah penyewaan terjadi pada pukul 04:00 dini hari ketika aktivitas masyarakat sedang berhenti.
- **Conclusion Pertanyaan 2:** Musim memiliki dampak yang signifikan terhadap penyewaan sepeda. Musim Gugur (*Fall*) mencatat total penyewaan tertinggi, yang kemungkinan besar menawarkan cuaca paling ideal untuk bersepeda. Sebaliknya, Musim Semi (*Springer*) merupakan periode dengan tingkat penyewaan terendah.
- **Conclusion Pertanyaan 3:** Performa bisnis menunjukkan tren yang sangat baik. Terdapat pola musiman yang konsisten di mana penyewaan selalu meningkat di pertengahan hingga akhir tahun (Kuartal 2 & 3). Selain itu, terjadi lonjakan pertumbuhan penyewaan (*Year-over-Year growth*) yang sangat masif dari tahun 2011 ke tahun 2012 di semua kuartal.
- **Conclusion Pertanyaan 4:** Bisnis *bike sharing* ini sangat ditopang oleh pelanggan setia. Pengguna terdaftar (*Registered*) mendominasi dengan menyumbang 81.2% dari total penyewaan (lebih dari 2,6 juta kali), dibandingkan pengguna biasa (*Casual*) yang hanya 18.8%. Meskipun begitu, kedua segmen pengguna ini sama-sama mengalami pertumbuhan yang pesat dari tahun ke tahun.
- **Conclusion Analisis Lanjutan (Clustering):** Melalui pengelompokan waktu (*binning*), terkonfirmasi bahwa kategori waktu *Afternoon* (12:00 - 16:59) dan *Evening* (17:00 - 20:59) adalah penyumbang trafik penyewaan terbesar, mengungguli kategori pagi dan malam hari.